name: Build Arbeitsberichte PDF

on:
  push:
    paths:
      - 'docs/Fächer/Arbeitsberichte/**.md'

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: PDF-Erstellung installieren
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-latex-extra texlive-fonts-recommended

      - name: PDF bauen
        run: |
          mkdir -p output
          pandoc docs/Fächer/Arbeitsberichte/arbeitsberichte.md -o output/arbeitsberichte.pdf

      - name: PDF auf OneDrive hochladen
        uses: dawidd6/action-upload-to-onedrive@v3
        with:
          folder-id: ${{ secrets.ONEDRIVE_FOLDER_ID }}
          client-id: ${{ secrets.ONEDRIVE_CLIENT_ID }}
          client-secret: ${{ secrets.ONEDRIVE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.ONEDRIVE_REFRESH_TOKEN }}
          source: output/arbeitsberichte.pdf
